### ISSUE TITLE
Prettify code

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [jctaoo/electron-run#53]
Hey, I was looking to update prettier to latest, and when it does, it needs to prettify a lot of files. I was thinking into maybe baking it into github actions, like this:

```yml
# File ".github/workflows/CI.yml"
# [...]
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install
          yarn global add npm-publish

# New code:
      - name: Prettify code
        run: |
          echo "Prettifying code"
          yarn fix:prettier --loglevel silent
# End of new code.

      - name: install dependencies for fixtures
        run: |
          cd fixtures/demo
          yarn install
          cd ../../
# [...]
```
What are your thoughts?
